### ISSUE TITLE
Ubuntu 12.04 - Startup Error

### ISSUE THREAD

**Issue by jayd3e** [flynn-archive/flynn-controller#3] opened 2014-03-13 13:09 UTC
When I attempt to run 'bin/flynn-controller' on a machine, I get the following error:

```
ubuntu@<lawl>:~/flynn-dev$ bin/flynn-controller 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4798eb]

goroutine 6 [running]:
runtime.panic(0x6b1300, 0xa3baa8)
    /usr/local/go/src/pkg/runtime/panic.c:266 +0xb6
github.com/flynn/go-flynn/cluster.func·003(0x0, 0x0)
    /home/ubuntu/flynn-dev/src/github.com/flynn/go-flynn/cluster/client.go:43 +0xbb
github.com/flynn/go-flynn/attempt.Strategy.Run(0x12a05f200, 0xbebc200, 0x5, 0x7f2b111b3f70, 0x0, ...)
    /home/ubuntu/flynn-dev/src/github.com/flynn/go-flynn/attempt/attempt.go:26 +0x7f
github.com/flynn/go-flynn/cluster.(*Client).followLeader(0xc21001fcd0, 0xc210038ae0)
    /home/ubuntu/flynn-dev/src/github.com/flynn/go-flynn/cluster/client.go:45 +0x11a
created by github.com/flynn/go-flynn/cluster.NewClient
    /home/ubuntu/flynn-dev/src/github.com/flynn/go-flynn/cluster/client.go:32 +0xec

goroutine 1 [chan receive]:
github.com/flynn/go-flynn/cluster.NewClient(0x7f2b11332000, 0x4861c6, 0x6a1f60)
    /home/ubuntu/flynn-dev/src/github.com/flynn/go-flynn/cluster/client.go:33 +0x105
main.main()
    /home/ubuntu/flynn-dev/src/github.com/flynn/flynn-controller/server.go:22 +0x26

goroutine 4 [IO wait]:
net.runtime_pollWait(0x7f2b1133c5d8, 0x72, 0x0)
    /usr/local/go/src/pkg/runtime/netpoll.goc:116 +0x6a
net.(*pollDesc).Wait(0xc21004ec30, 0x72, 0x7f2b1133b0c0, 0xb)
    /usr/local/go/src/pkg/net/fd_poll_runtime.go:81 +0x34
net.(*pollDesc).WaitRead(0xc21004ec30, 0xb, 0x7f2b1133b0c0)
    /usr/local/go/src/pkg/net/fd_poll_runtime.go:86 +0x30
net.(*netFD).Read(0xc21004ebd0, 0xc210071000, 0x1000, 0x1000, 0x0, ...)
    /usr/local/go/src/pkg/net/fd_unix.go:204 +0x2a0
net.(*conn).Read(0xc210000358, 0xc210071000, 0x1000, 0x1000, 0xc21006b092, ...)
    /usr/local/go/src/pkg/net/net.go:122 +0xc5
bufio.(*Reader).fill(0xc210038480)
    /usr/local/go/src/pkg/bufio/bufio.go:91 +0x110
bufio.(*Reader).Read(0xc210038480, 0xc21000abb0, 0x1, 0x9, 0x1, ...)
    /usr/local/go/src/pkg/bufio/bufio.go:159 +0x1a4
io.ReadAtLeast(0x7f2b1133c720, 0xc210038480, 0xc21000abb0, 0x1, 0x9, ...)
    /usr/local/go/src/pkg/io/io.go:288 +0xf6
io.ReadFull(0x7f2b1133c720, 0xc210038480, 0xc21000abb0, 0x1, 0x9, ...)
    /usr/local/go/src/pkg/io/io.go:306 +0x71
encoding/gob.decodeUintReader(0x7f2b1133c720, 0xc210038480, 0xc21000abb0, 0x9, 0x9, ...)
    /usr/local/go/src/pkg/encoding/gob/decode.go:66 +0x98
encoding/gob.(*Decoder).recvMessage(0xc210057000, 0xc210037270)
    /usr/local/go/src/pkg/encoding/gob/decoder.go:73 +0x57
encoding/gob.(*Decoder).decodeTypeSequence(0xc210057000, 0xc21006ab00, 0x160)
    /usr/local/go/src/pkg/encoding/gob/decoder.go:159 +0x49
encoding/gob.(*Decoder).DecodeValue(0xc210057000, 0x618ce0, 0xc21006ab40, 0x160, 0x0, ...)
    /usr/local/go/src/pkg/encoding/gob/decoder.go:223 +0x12e
encoding/gob.(*Decoder).Decode(0xc210057000, 0x618ce0, 0xc21006ab40, 0x0, 0x1)
    /usr/local/go/src/pkg/encoding/gob/decoder.go:202 +0x1c5
github.com/flynn/rpcplus.(*gobClientCodec).ReadResponseHeader(0xc21006ac90, 0xc21006ab40, 0x120, 0x618720)
    /home/ubuntu/flynn-dev/src/github.com/flynn/rpcplus/client.go:277 +0x3f
github.com/flynn/rpcplus.(*Client).input(0xc2100384e0)
    /home/ubuntu/flynn-dev/src/github.com/flynn/rpcplus/client.go:137 +0xb8
created by github.com/flynn/rpcplus.NewClientWithCodec
    /home/ubuntu/flynn-dev/src/github.com/flynn/rpcplus/client.go:255 +0x91

goroutine 5 [chan receive]:
github.com/flynn/go-discoverd.func·001()
    /home/ubuntu/flynn-dev/src/github.com/flynn/go-discoverd/client.go:123 +0x5b
created by github.com/flynn/go-discoverd.(*serviceSet).bind
    /home/ubuntu/flynn-dev/src/github.com/flynn/go-discoverd/client.go:163 +0xcf

goroutine 7 [chan receive]:
github.com/flynn/go-discoverd.func·002()
    /home/ubuntu/flynn-dev/src/github.com/flynn/go-discoverd/client.go:229 +0x8d
created by github.com/flynn/go-discoverd.(*serviceSet).Leaders
    /home/ubuntu/flynn-dev/src/github.com/flynn/go-discoverd/client.go:235 +0xef
```

I'm not sure if it's anything of concern, but I thought I would mention it.  I should note that this occurred through running `forego start` w/ sudo, and additionally when I attempted to run etcd, discoverd, and flynn-controller separately it happened as well.  If there is a bug, it seems to be in rpcplus with the way it creates new clients.  Really curious at this point what I overlooked.  What's the best way to debug go code these days?  I've tried using gdb but it's a little unwieldily(I mean compared to pdb, what I'm used to).  Is there a way to stick breakpoints right in the code?

**Comment by titanous** [comment] 2014-03-13 13:13
This is a duplicate of flynn/go-discoverd#22 (which is really a bug in go-flynn, I'm about to fix it).

It happened because no flynn-host services were available.

As far as debugging goes, I tend to just use print statements, since gdb has some serious issues :/

**Closed as completed by titanous** 2014-03-13 13:13 UTC

**Comment by jayd3e** [comment] 2014-03-13 13:20
Heh that was fast, good to know.  Great work!
